import React, { useState } from 'react'
import { Linkedin, Instagram, Menu, X } from 'lucide-react'
import LuxuryBackground from './components/LuxuryBackground'

export default function PrivacyPolicy() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  return (
    <LuxuryBackground>
      <div className="legal-page">
        <header className="main-header">
        <div className="header-content">
          <div className="logo-brand">
            <a href="/">
              <img src="/logo skinova.jpg" alt="Skinova" className="brand-logo" />
              <span className="brand-name">SKINOVA</span>
            </a>
          </div>
          <nav className="header-nav">
            <a href="/">Home</a>
            <a href="/#features">Features</a>
            <a href="/#about">About</a>
            <a href="/#contact">Contact</a>
          </nav>
          <div className="header-right">
            <div className="header-downloads">
              <img src="/download app store.png" alt="Download App" className="download-stores" />
            </div>
            <button 
              className="mobile-menu-toggle"
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              aria-label="Toggle menu"
            >
              {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
            </button>
          </div>
        </div>
        
        {/* Mobile Menu */}
        {isMobileMenuOpen && (
          <div className="mobile-menu">
            <a href="/" onClick={() => setIsMobileMenuOpen(false)}>Home</a>
            <a href="/#features" onClick={() => setIsMobileMenuOpen(false)}>Features</a>
            <a href="/#about" onClick={() => setIsMobileMenuOpen(false)}>About</a>
            <a href="/#contact" onClick={() => setIsMobileMenuOpen(false)}>Contact</a>
          </div>
        )}
      </header>

      <div className="legal-content">
        <div className="legal-container">
          <h1>Privacy Policy</h1>
          <p className="last-updated">Last Updated: November 28, 2025</p>
          <p>
            This Privacy Policy describes how Skinova, Inc. ("the Company", "We", "Us", or "Our") collects, uses, processes, shares, and protects Your information when You use the Skinova mobile application, website, and related services (collectively, the "Service").
            <br />
            By using the Service, You agree to the practices described in this Privacy Policy.
          </p>
          

          
          <br></br>
          <section className="legal-section">
            <h2>1. Interpretation and Definitions</h2>
            <h3>1.1 Interpretation</h3>
            <p>Capitalized terms have the meanings assigned to them in this Policy.</p>
            
            <h3>1.2 Definitions</h3>
            <ul>
              <li><strong>Account</strong> – The unique profile created for You to access the Service.</li>
              <li><strong>Application</strong> – The mobile application titled "Skinova – AI Skin Analyzer".</li>
              <li><strong>Biometric Data</strong> – Facial measurements generated by Our AI during skin analysis (not used for identification).</li>
              <li><strong>Company</strong> – Skinova, Inc., with mailing address.</li>
              <li><strong>Device</strong> – Any device used to access the Service.</li>
              <li><strong>Personal Data</strong> – Information that identifies or can reasonably be linked to an individual.</li>
              <li><strong>Skin Data</strong> – Information relating to Your facial characteristics, skin conditions, photos, skincare goals, routines, and product history.</li>
              <li><strong>User Content</strong> – Photos, images, text entries, or other data You upload.</li>
              <li><strong>Website</strong> – skinova.app .</li>
              <li><strong>You</strong> – The individual using the Service.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>2. Data We Collect</h2>
            
            <h3>2.1 Personal Data You Provide</h3>
            <ul>
              <li>First name</li>
              <li>Last name</li>
              <li>Email address</li>
              <li>Optional profile data (age range, gender, skincare goals)</li>
            </ul>

            <h3>2.2 Skin and Facial Data</h3>
            <p>To analyze your skin, Skinova collects:</p>
            <ul>
              <li>Face photos</li>
              <li>Detected skin conditions (acne, pores, wrinkles, texture, pigmentation, etc.)</li>
              <li>Skin type estimations</li>
              <li>Skin health progression</li>
              <li>Skincare goals</li>
              <li>Past routines and product usage</li>
            </ul>
            <p><strong>Important:</strong></p>
            <ul>
              <li>We do not create or store facial biometrics for identity verification.</li>
              <li>Your face is used only for skin analysis.</li>
            </ul>

            <h3>2.3 AI Model Data (Biometric-Adjacent)</h3>
            <p>Skinova's AI generates numerical facial maps used only for:</p>
            <ul>
              <li>Skin evaluation</li>
              <li>Progress tracking</li>
              <li>Routine personalization</li>
              <li>Not for identifying users.</li>
            </ul>

            <h3>2.4 User Content</h3>
            <p>Includes:</p>
            <ul>
              <li>Facial photos</li>
              <li>Skin notes</li>
              <li>Routine details</li>
              <li>Skincare feedback</li>
            </ul>
            <p>You may allow anonymized photos to be used to improve AI models (optional).</p>

            <h3>2.5 Usage Data</h3>
            <p>Automatically collected:</p>
            <ul>
              <li>Device model and OS</li>
              <li>IP address</li>
              <li>App version</li>
              <li>Crash logs</li>
              <li>Feature usage analytics</li>
              <li>Session information</li>
            </ul>

            <h3>2.6 Cookies and Tracking</h3>
            <p>The Website uses cookies for analytics and security.</p>
          </section>

          <section className="legal-section">
            <h2>3. How We Use Your Data</h2>
            
            <h3>3.1 Provide and Improve Skinova Services</h3>
            <p>We use Your data to:</p>
            <ul>
              <li>Analyze your skin with AI algorithms</li>
              <li>Detect skin imperfections</li>
              <li>Deliver skincare routines</li>
              <li>Recommend skincare products</li>
              <li>Track skin progress</li>
              <li>Maintain app functionality</li>
              <li>Prevent or fix bugs</li>
            </ul>

            <h3>3.2 Improve AI Skin Models (Only with Consent)</h3>
            <p>Anonymized photos may be used to:</p>
            <ul>
              <li>Train Skinova's AI</li>
              <li>Improve skin detection accuracy</li>
              <li>Support product recommendations</li>
            </ul>
            <p>Photos used for training are never linked to your identity.</p>

            <h3>3.3 Communications</h3>
            <p>We may send:</p>
            <ul>
              <li>Skin analysis results</li>
              <li>Feature updates</li>
              <li>Support responses</li>
            </ul>

            <h3>3.4 Marketing (Optional)</h3>
            <p>With your permission, we may send:</p>
            <ul>
              <li>Skincare tips</li>
              <li>Product offers</li>
              <li>Skinova features & updates</li>
            </ul>

            <h3>3.5 Legal and Compliance</h3>
            <p>To:</p>
            <ul>
              <li>Prevent fraud</li>
              <li>Comply with legal obligations</li>
              <li>Protect the Company's rights</li>
            </ul>

            <h3>3.6 Business Transfers</h3>
            <p>If Skinova is acquired or merged, your data may transfer as allowed by law.</p>
          </section>

          <section className="legal-section">
            <h2>4. GDPR Legal Bases</h2>
            <p>When applicable, Skinova processes data under:</p>
            <ul>
              <li>Consent (photos, analysis)</li>
              <li>Contract performance</li>
              <li>Legitimate interest</li>
              <li>Legal obligations</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>5. Sharing Personal Data</h2>
            <p>We share data only with:</p>

            <h3>5.1 Service Providers</h3>
            <p>Such as:</p>
            <ul>
              <li>Cloud storage (for photos)</li>
              <li>AI processing tools</li>
              <li>Support platforms</li>
              <li>Analytics services</li>
            </ul>

            <h3>5.2 Business Transfers</h3>
            <p>If legally required during acquisition or restructuring.</p>

            <h3>5.3 Legal Compliance</h3>
            <p>When required by law enforcement or regulations.</p>

            <h3>5.4 With Your Consent</h3>
            <p>If you request specific sharing.</p>

            <h3>5.5 Aggregated or Anonymized Data</h3>
            <p>We may share anonymized, non-identifiable data for analytics and research.</p>
            
            <p><strong>Skinova does NOT sell your Personal Data.</strong></p>
          </section>

          <section className="legal-section">
            <h2>6. User Content Rights</h2>
            <p>By uploading photos or content, You grant Skinova a limited license to:</p>
            <ul>
              <li>Process and analyze your images</li>
              <li>Provide results, recommendations, and routines</li>
              <li>Improve app performance</li>
            </ul>
            <p>We will never display your photos publicly without explicit consent.</p>
            <p>Photos used for AI training are optional and fully anonymized.</p>
          </section>

          <section className="legal-section">
            <h2>7. Data Retention</h2>
            <p>We retain:</p>
            <ul>
              <li>Personal Data while your Account is active</li>
              <li>Photos and analysis only until you delete them</li>
              <li>Backups for limited periods</li>
            </ul>
            <p>You can delete any data at any time.</p>
          </section>

          <section className="legal-section">
            <h2>8. International Data Transfers</h2>
            <p>Your data may be processed outside your country.</p>
            <p>We use legal safeguards such as Standard Contractual Clauses.</p>
          </section>

          <section className="legal-section">
            <h2>9. Your Privacy Rights</h2>
            <p>You have rights to:</p>
            <ul>
              <li>Access Your data</li>
              <li>Correct inaccuracies</li>
              <li>Delete Your Personal Data</li>
              <li>Export Your data</li>
              <li>Withdraw consent</li>
              <li>Restrict processing</li>
            </ul>
            <p>Contact us at support@skinova.app (or your final email).</p>
          </section>

          <section className="legal-section">
            <h2>10. Data Deletion</h2>
            <p>You may delete:</p>
            <ul>
              <li>Face photos</li>
              <li>Skin analysis history</li>
              <li>Skincare routines</li>
              <li>Your entire Account</li>
            </ul>
            <p>Certain data may remain in backups for legal compliance.</p>
          </section>

          <section className="legal-section">
            <h2>11. Security</h2>
            <p>
              We use strong administrative, physical, and technical safeguards to protect Your data, 
              but no system is entirely secure.
            </p>
          </section>

          <section className="legal-section">
            <h2>12. Children's Privacy</h2>
            <p>Skinova is not intended for children under 13.</p>
            <p>We do not knowingly collect children's data.</p>
          </section>

          <section className="legal-section">
            <h2>13. Third-Party Links</h2>
            <p>External websites or services are not controlled by Us.</p>
            <p>Their privacy practices are their own.</p>
          </section>

          <section className="legal-section">
            <h2>14. Changes to This Privacy Policy</h2>
            <p>We may update this Policy.</p>
            <p>Changes take effect when posted in the Application or Website.</p>
            <p>Major updates may be communicated.</p>
          </section>

          <section className="legal-section">
            <h2>15. Contact Us</h2>
            <p>For questions or requests:</p>
            <p>📧 support@skinova.app</p>
          </section>

          <div className="legal-back">
            <a href="/" className="back-button">← Back to Home</a>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="footer">
        <div className="footer-main">
          <div className="footer-brand-section">
            <div className="footer-logo">
              <img src="/logo skinova.jpg" alt="SKINOVA" className="footer-logo-img" />
              <span className="footer-brand-name">SKINOVA</span>
            </div>
            <p className="footer-download-text">Download SKINOVA</p>
            <div className="footer-app-buttons">
              <a href="#" target="_blank" rel="noopener noreferrer">
                <img src="/download app store.png" alt="Download App" className="footer-store-badge" />
              </a>
            </div>
          </div>

          <div className="footer-links-center">
            <div className="footer-links-section">
              <div className="footer-column">
                <h4>Legal</h4>
                <a href="/privacy-policy">Privacy Policy</a>
                <a href="/terms-of-use">Terms of use</a>
              </div>

              <div className="footer-column">
                <h4>Company</h4>
                <a href="/contact">Contact</a>
              </div>
            </div>
          </div>

          <div className="footer-empty-section"></div>
        </div>

        <div className="footer-bottom">
          <p className="footer-copyright">© Copyright 2025, All rights reserved</p>
          <div className="footer-social">
            <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="social-link">
              <Linkedin size={20} />
            </a>
            <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" className="social-link">
              <Instagram size={20} />
            </a>
            <a href="https://tiktok.com" target="_blank" rel="noopener noreferrer" className="social-link">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-5.2 1.74 2.89 2.89 0 0 1 2.31-4.64 2.93 2.93 0 0 1 .88.13V9.4a6.84 6.84 0 0 0-1-.05A6.33 6.33 0 0 0 5 20.1a6.34 6.34 0 0 0 10.86-4.43v-7a8.16 8.16 0 0 0 4.77 1.52v-3.4a4.85 4.85 0 0 1-1-.1z"/>
              </svg>
            </a>
          </div>
        </div>
      </footer>
      </div>
    </LuxuryBackground>
  )
}
